CREATE TABLE APP (
    nombre VARCHAR2(100),
    fecha_creacion TIMESTAMP
)
[GO]

CREATE TABLE categorias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) UNIQUE NOT NULL,
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo VARCHAR2(255),
    usuario_modifico VARCHAR2(255)
)
[GO]

CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255) NOT NULL,
    email VARCHAR2(255),
    telefono VARCHAR2(100),
    direccion VARCHAR2(2000),
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo VARCHAR2(255),
    usuario_modifico VARCHAR2(255)
)
[GO]

CREATE TABLE config (
    nombre VARCHAR2(255) PRIMARY KEY,
    valor VARCHAR2(4000)
)
[GO]

CREATE TABLE desc_x_total_venta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id NUMBER,
    tipo VARCHAR2(100),
    monto BINARY_DOUBLE,
    detalle VARCHAR2(2000)
)
[GO]

CREATE TABLE historico_inventario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    proveedor_id NUMBER,
    numero_pedido VARCHAR2(255),
    accion VARCHAR2(255),
    "user" VARCHAR2(255),
    stock_actual BINARY_DOUBLE,
    nuevo_stock BINARY_DOUBLE,
    producto_id NUMBER
)
[GO]

CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(255) UNIQUE NOT NULL,
    codigo_proveedor VARCHAR2(255),
    nombre VARCHAR2(255) NOT NULL,
    descripcion VARCHAR2(2000),
    marca VARCHAR2(255),
    precio_compra BINARY_DOUBLE NOT NULL,
    precio_venta BINARY_DOUBLE NOT NULL,
    stock BINARY_DOUBLE DEFAULT 0 NOT NULL,
    proveedor_id NUMBER,
    categoria_id NUMBER,
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo VARCHAR2(255),
    usuario_modifico VARCHAR2(255),
    activo VARCHAR2(50),
    min_stock BINARY_DOUBLE DEFAULT 0
)
[GO]

CREATE TABLE proveedores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    telefono VARCHAR2(100),
    direccion VARCHAR2(2000),
    email VARCHAR2(255),
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo VARCHAR2(255),
    usuario_modifico VARCHAR2(255)
)
[GO]

CREATE TABLE tmp (
    producto_id NUMBER,
    cantidad_vendida BINARY_DOUBLE
)
[GO]

CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" VARCHAR2(255) UNIQUE NOT NULL,
    pass VARCHAR2(1000) NOT NULL,
    nombre VARCHAR2(255) NOT NULL,
    tipo VARCHAR2(50) NOT NULL
)
[GO]

CREATE TABLE venta_detalle (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    nombre_producto VARCHAR2(255) NOT NULL,
    precio BINARY_DOUBLE NOT NULL,
    cantidad BINARY_DOUBLE NOT NULL,
    total BINARY_DOUBLE NOT NULL,
    descuento BINARY_DOUBLE
)
[GO]

CREATE TABLE ventas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash VARCHAR2(255) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    total BINARY_DOUBLE NOT NULL,
    descuento BINARY_DOUBLE NOT NULL,
    descuento_detalle VARCHAR2(2000),
    total_a_pagar BINARY_DOUBLE NOT NULL,
    efectivo BINARY_DOUBLE NOT NULL,
    tarjeta BINARY_DOUBLE NOT NULL,
    cambio BINARY_DOUBLE NOT NULL,
    cliente_id NUMBER NOT NULL,
    factura_nit VARCHAR2(255),
    factura_nombre VARCHAR2(255),
    factura_email VARCHAR2(255),
    factura_telefono VARCHAR2(100),
    factura_direccion VARCHAR2(2000),
    enviar_factura VARCHAR2(50),
    estado VARCHAR2(50),
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo VARCHAR2(255),
    usuario_modifico VARCHAR2(255)
)
[GO]

INSERT INTO APP(nombre, fecha_creacion)
VALUES ('MINISTORE', CURRENT_TIMESTAMP)
[GO]

INSERT ALL
INTO config(nombre, valor) VALUES ('desc.x.venta.y.prod', 'Habilitado')
INTO config(nombre, valor) VALUES ('desc.x.venta.total', 'Habilitado')
INTO config(nombre, valor) VALUES ('desc.x.cliente', 'Habilitado')
INTO config(nombre, valor) VALUES ('desc.x.producto', 'Habilitado')
INTO config(nombre, valor) VALUES ('app.name', 'MiniStore')
INTO config(nombre, valor) VALUES ('app.logo', 'res/logo.png')
INTO config(nombre, valor) VALUES ('app.currency', 'Q')
INTO config(nombre, valor) VALUES ('app.product.page.size', '40')
INTO config(nombre, valor) VALUES ('app.log.file', 'app.log')
INTO config(nombre, valor) VALUES ('app.payment.method', 'CASH')
INTO config(nombre, valor) VALUES ('app.product.code.prefix', 'M')
INTO config(nombre, valor) VALUES ('app.product.code.starts', '7001')
INTO config(nombre, valor) VALUES ('app.ui.font.size', '13')
INTO config(nombre, valor) VALUES ('app.print.font.size', '10')
INTO config(nombre, valor) VALUES ('app.invoice.header', 'MINI STORE
<ubicacion>
* Comprobante *
Cliente: ${nit_cliente} - ${nombre_cliente}
Asesor: ${asesor}
Fecha y hora: ${fecha_y_hora}
')
INTO config(nombre, valor) VALUES ('app.invoice.footer', ' ¡Ha sido un placer atenderle! ')
SELECT 1 FROM dual
[GO]
