-- APP definition
CREATE TABLE APP(
    nombre TEXT,
    fecha_creacion TIMESTAMP
)
[GO]


-- categorias definition
CREATE TABLE categorias (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre TEXT UNIQUE NOT NULL,
       fecha_creacion TIMESTAMP,
       fecha_modificacion TIMESTAMP,
       usuario_creo TEXT,
       usuario_modifico TEXT
)
[GO]


-- clientes definition
CREATE TABLE clientes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento TEXT NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT,
    telefono TEXT,
    direccion TEXT,
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo TEXT,
    usuario_modifico TEXT
)
[GO]


-- config definition
CREATE TABLE config(
    nombre TEXT PRIMARY KEY,
    valor TEXT
)
[GO]


-- desc_x_total_venta definition
CREATE TABLE desc_x_total_venta(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER,
    tipo TEXT,
    monto DOUBLE PRECISION,
    detalle TEXT
)
[GO]


-- historico_inventario definition
CREATE TABLE historico_inventario (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       fecha TIMESTAMP NOT NULL,
       proveedor_id INTEGER,
       numero_pedido TEXT,
       accion TEXT,
       "user" TEXT,
       stock_actual DOUBLE PRECISION,
       nuevo_stock DOUBLE PRECISION,
       producto_id INTEGER
)
[GO]


-- productos definition
CREATE TABLE productos (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       codigo TEXT UNIQUE NOT NULL,
       codigo_proveedor TEXT,
       nombre TEXT NOT NULL,
       descripcion TEXT,
       marca TEXT,
       precio_compra DOUBLE PRECISION NOT NULL,
       precio_venta DOUBLE PRECISION NOT NULL,
       stock DOUBLE PRECISION NOT NULL DEFAULT 0,
       proveedor_id INTEGER,
       categoria_id INTEGER,
       fecha_creacion TIMESTAMP,
       fecha_modificacion TIMESTAMP,
       usuario_creo TEXT,
       usuario_modifico TEXT,
       activo TEXT,
       min_stock DOUBLE PRECISION DEFAULT 0
)
[GO]


-- proveedores definition
CREATE TABLE proveedores (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre TEXT NOT NULL,
       telefono TEXT,
       direccion TEXT,
       email TEXT,
       fecha_creacion TIMESTAMP,
       fecha_modificacion TIMESTAMP,
       usuario_creo TEXT,
       usuario_modifico TEXT
)
[GO]


-- tmp definition
CREATE TABLE tmp(
    producto_id INTEGER,
    cantidad_vendida DOUBLE PRECISION
)
[GO]


-- usuario definition
CREATE TABLE usuario(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" TEXT UNIQUE NOT NULL,
    pass TEXT NOT NULL,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL
)
[GO]


-- venta_detalle definition
CREATE TABLE venta_detalle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL,
    producto_id INTEGER NOT NULL,
    nombre_producto TEXT NOT NULL,
    precio DOUBLE PRECISION NOT NULL,
    cantidad DOUBLE PRECISION NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    descuento DOUBLE PRECISION
)
[GO]


-- ventas definition
CREATE TABLE ventas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    descuento DOUBLE PRECISION NOT NULL,
    descuento_detalle TEXT,
    total_a_pagar DOUBLE PRECISION NOT NULL,
    efectivo DOUBLE PRECISION NOT NULL,
    tarjeta DOUBLE PRECISION NOT NULL,
    cambio DOUBLE PRECISION NOT NULL,
    cliente_id INTEGER NOT NULL,
    factura_nit TEXT,
    factura_nombre TEXT,
    factura_email TEXT,
    factura_telefono TEXT,
    factura_direccion TEXT,
    enviar_factura TEXT,
    estado TEXT,
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    usuario_creo TEXT,
    usuario_modifico TEXT
)
[GO]


INSERT INTO APP(nombre, fecha_creacion)
VALUES ('MINISTORE', CURRENT_TIMESTAMP)
[GO]


INSERT INTO config(nombre, valor) VALUES
('desc.x.venta.y.prod',     'Habilitado'),
('desc.x.venta.total',      'Habilitado'),
('desc.x.cliente',          'Habilitado'),
('desc.x.producto',         'Habilitado'),
('app.name',                'MiniStore'),
('app.logo',                'res/logo.png'),
('app.currency',            'Q'),
('app.product.page.size',   '40'),
('app.log.file',            'app.log'),
('app.payment.method',      'CASH'),
('app.product.code.prefix', 'M'),
('app.product.code.starts', '7001'),
('app.ui.font.size',        '13'),
('app.print.font.size',     '10'),
('app.invoice.header',      'MINI STORE
<ubicacion>
* Comprobante *
Cliente: ${nit_cliente} - ${nombre_cliente}
Asesor: ${asesor}
Fecha y hora:  ${fecha_y_hora}
'),
('app.invoice.footer',      ' ¡Ha sido un placer atenderle! ')
[GO]
