package com.lasopro.ministore.desktop;

import com.lasopro.ministore.util.Resources;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author williams
 */
public class DialogVentaDetalle extends javax.swing.JDialog {
    
    private static DialogVentaDetalle me = null;
    private Map<String,Object> info;
    /**
     * Creates new form DialogVentaDetalle
     */
    private DialogVentaDetalle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        this.setLocationByPlatform(true);
    }
    
    
    public static void mostrar(Map<String,Object> info, boolean editable){
        
        if(me == null){
            me = new DialogVentaDetalle(MinistoreDesktop.getMainFrame(), true);
        }
        
        
        me.tDescuento.setEditable(Resources.p("desc.x.venta.y.prod").equalsIgnoreCase("Habilitado"));
        
        
        me.info = info;
        
        Double precio    =  (Double)info.get("precio");
        Double descuento    =  (Double)info.get("descuento");
        descuento = descuento == null ? 0d : descuento;
        
        me.tCantidad.setText(info.get("cantidad")+"");
        me.tPrecio.setText(precio+"");
        me.tDescuento.setText(descuento+"");
        me.tPrecioConDescuento.setText((precio-descuento)+"");
        
        me.tCantidad.requestFocus();
        me.tCantidad.select(0, me.tCantidad.getText().length());
        
        me.lNombreProducto.setText("<html><p style='text-align:center'>"+info.get("codigo")+"<br/>"+info.get("nombre")+(info.get("descripcion") != null ? "<br/> ("+info.get("descripcion")+")":"")+"</p></html>");
        
        me.tCantidad.setEditable(editable);
        me.tDescuento.setEditable(editable && Resources.p("desc.x.venta.y.prod").equalsIgnoreCase("Habilitado"));
        me.bAceptar.setEnabled(editable);
        
        me.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lCantidad = new javax.swing.JLabel();
        tCantidad = new javax.swing.JTextField();
        lPrecio = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tDescuento = new javax.swing.JTextField();
        lDescuento = new javax.swing.JLabel();
        lNombreProducto = new javax.swing.JLabel();
        lPrecioConDescuento = new javax.swing.JLabel();
        tPrecioConDescuento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lCantidad.setText("Cantidad:");

        tCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCantidadFocusGained(evt);
            }
        });

        lPrecio.setText("<html>Precio<br/>unitario:</html>");

        tPrecio.setEditable(false);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cerrar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tDescuentoFocusGained(evt);
            }
        });
        tDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tDescuentoKeyReleased(evt);
            }
        });

        lDescuento.setText("Descuento:");

        lNombreProducto.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreProducto.setText("Nombre producto");

        lPrecioConDescuento.setText("<html>Precio con<br/>descuento:</html>");

        tPrecioConDescuento.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lDescuento)
                    .addComponent(lCantidad)
                    .addComponent(lPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar))
                    .addComponent(tDescuento)
                    .addComponent(tPrecio)
                    .addComponent(tCantidad)
                    .addComponent(tPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(lNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        info.put("cantidad", Double.valueOf(tCantidad.getText()));
        info.put("descuento", Double.valueOf(tDescuento.getText()));
        double cantidad = Double.parseDouble(tCantidad.getText());
        double precio = Double.parseDouble(tPrecio.getText());
        double descuento = Double.parseDouble(tDescuento.getText());
        info.put("total", cantidad * (precio - descuento));
        this.setVisible(false);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDescuentoKeyReleased
        Double precioConDescuento  = 0d;
        try {
            precioConDescuento = Double.valueOf(tPrecio.getText());
            precioConDescuento = precioConDescuento - Double.valueOf(tDescuento.getText());
        } catch (Throwable e) {}
        tPrecioConDescuento.setText(precioConDescuento+"");
    }//GEN-LAST:event_tDescuentoKeyReleased

    private void tDescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescuentoFocusGained
        try {
            ((JTextField)evt.getSource()).select(0, ((JTextField)evt.getSource()).getText().length());
        } catch (Exception e) {}
    }//GEN-LAST:event_tDescuentoFocusGained

    private void tCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCantidadFocusGained
        try {
            ((JTextField)evt.getSource()).select(0, ((JTextField)evt.getSource()).getText().length());
        } catch (Exception e) {}
    }//GEN-LAST:event_tCantidadFocusGained

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCantidad;
    private javax.swing.JLabel lDescuento;
    private javax.swing.JLabel lNombreProducto;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JLabel lPrecioConDescuento;
    private javax.swing.JTextField tCantidad;
    private javax.swing.JTextField tDescuento;
    private javax.swing.JTextField tPrecio;
    private javax.swing.JTextField tPrecioConDescuento;
    // End of variables declaration//GEN-END:variables
}
