package com.lasopro.ministore.desktop;

import com.lasopro.ministore.db.Ventas;
import com.lasopro.ministore.util.Util;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author williams
 */
public class PanelVentas extends javax.swing.JPanel implements PanelInterface {

    
    Ventas db = new Ventas();
    
    
    /**
     * Creates new form PanelVentas
     */
    public PanelVentas() {
        initComponents();
        configurarAtajoNuevaVenta();
        this.panelVenta1.setParent(PanelVentas.this);
        this.panelVenta1.setVisible(false);
    }

    private void configurarAtajoNuevaVenta() {
        btNuevaVenta.setText("Nueva venta [F5]");
        getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "nuevaVenta");
        getActionMap().put("nuevaVenta", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent event) {
                if (btNuevaVenta.isVisible() && btNuevaVenta.isEnabled()) {
                    btNuevaVenta.doClick();
                }
            }
        });
    }
    
    
    
    
    public void llenarHistoricoVentas(){
        
        String mostrar = (String)cbMostrarHis.getSelectedItem();
        
        if(mostrar == null) mostrar = "Hoy";
        
        Calendar c = Calendar.getInstance();
        c.set(Calendar.HOUR_OF_DAY, 0);
        c.set(Calendar.MINUTE, 0);
        c.set(Calendar.SECOND, 0);
        c.set(Calendar.MILLISECOND, 0);
        List<Map<String,Object>> list;
        switch(mostrar){
            case "Hoy": 
                list = db.listByDate(new java.sql.Date(c.getTimeInMillis()));
                break;
            case "Últimos 7 días": 
                c.add(Calendar.DAY_OF_MONTH, -7);
                list = db.listByDate(new java.sql.Date(c.getTimeInMillis()));
                break;
            case "Últimos 30 días": 
                c.add(Calendar.DAY_OF_MONTH, -30);
                list = db.listByDate(new java.sql.Date(c.getTimeInMillis()));
                break;
            case "Últimos 6 meses": 
                c.add(Calendar.MONTH, -6);
                list = db.listByDate(new java.sql.Date(c.getTimeInMillis()));
                break;
            default:
                list = db.listByDate(new java.sql.Date(c.getTimeInMillis()));
                break;
        }
        
        DefaultListModel<Venta> model = new DefaultListModel<>();
        
        if(list.size() > 1000){
            JOptionPane.showMessageDialog(this, "Se encontraron "+list.size()+" ventas, se mostraran únicamente las últimas 1000.");
        }
        
        for(int i = 0; i < list.size() && i < 1000 ; i++){
            Map<String,Object> m = list.get(i);
            model.addElement(new Venta(m));
        }
        jList1.setModel(model);
        
    }
    
    
    public boolean isVentaEnCurso(){
        return this.panelVenta1.isVentaEnCurso();
    }
    
    
    @Override
    public String name() {
        return "ventas";
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentasDia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cbMostrarHis = new javax.swing.JComboBox<>();
        btNuevaVenta = new javax.swing.JButton();
        lTituloVenta = new javax.swing.JLabel();
        panelVenta1 = new com.lasopro.ministore.desktop.PanelVenta();

        setBackground(new java.awt.Color(255, 255, 255));

        panelVentasDia.setBackground(new java.awt.Color(255, 255, 255));
        panelVentasDia.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico de ventas"));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        cbMostrarHis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Últimos 7 días", "Últimos 30 días", "Últimos 6 meses" }));
        cbMostrarHis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbMostrarHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarHisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVentasDiaLayout = new javax.swing.GroupLayout(panelVentasDia);
        panelVentasDia.setLayout(panelVentasDiaLayout);
        panelVentasDiaLayout.setHorizontalGroup(
            panelVentasDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentasDiaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(cbMostrarHis, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelVentasDiaLayout.setVerticalGroup(
            panelVentasDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentasDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMostrarHis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
        );

        btNuevaVenta.setBackground(new java.awt.Color(0, 0, 153));
        btNuevaVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btNuevaVenta.setText("Nueva venta [+]");
        btNuevaVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5));
        btNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaVentaActionPerformed(evt);
            }
        });

        lTituloVenta.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTituloVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelVenta1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVentasDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btNuevaVenta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lTituloVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelVenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaVentaActionPerformed
        this.btNuevaVenta.setVisible(false);
        this.panelVenta1.iniciarNuevaVenta();
        this.panelVenta1.setVisible(true);
        this.lTituloVenta.setText("Nueva venta");
        this.panelVenta1.focusOnInputText();
    }//GEN-LAST:event_btNuevaVentaActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        
        if(this.panelVenta1.isVentaEnCurso()){
            JOptionPane.showMessageDialog(this, "Hay una venta en curso, Finalice o Aborte la venta para poder visualizar", "Venta en curso", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(jList1.getSelectedValue() == null){
            return;
        }
        
        MinistoreDesktop.runInThread("Cargando datos de venta seleccionada...", ()->{
            this.panelVenta1.mostrarVenta(jList1.getSelectedValue().info);
            this.lTituloVenta.setText(jList1.getSelectedValue().toString().replace("<br/>",""));
            this.panelVenta1.setVisible(true);
        });
    }//GEN-LAST:event_jList1ValueChanged

    private void cbMostrarHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarHisActionPerformed
        llenarHistoricoVentas();
    }//GEN-LAST:event_cbMostrarHisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNuevaVenta;
    private javax.swing.JComboBox<String> cbMostrarHis;
    private javax.swing.JList<Venta> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTituloVenta;
    private com.lasopro.ministore.desktop.PanelVenta panelVenta1;
    private javax.swing.JPanel panelVentasDia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(){
        MinistoreDesktop.runInThread("Actualizando datos...",()->{
            _refresh();
        });
    }

    public void _refresh() {        
        this.panelVenta1.fullRefresh();
        this.btNuevaVenta.setVisible(!this.panelVenta1.isVentaEnCurso());
        this.llenarHistoricoVentas();
    }


    public void lightRefresh(){
        MinistoreDesktop.runInThread("Actualizando datos...",()->{
            this.panelVenta1.refresh();
            this.btNuevaVenta.setVisible(!this.panelVenta1.isVentaEnCurso());
            this.llenarHistoricoVentas();
        });
    }
    
    static class Venta{
        
        Map<String,Object> info;
        
        Venta(Map<String,Object> info){
            this.info = info;
        }

        @Override
        public String toString() {

            try {
            
                Date fecha = (Date)info.get("fecha");
                Double monto = ((Number)info.get("total")).doubleValue();
                monto = monto - ((Number)info.get("descuento")).doubleValue();
                String estado  = (String)info.get("estado");

                String color = "Anulada".equalsIgnoreCase(estado)?"red":"green";
                String fh = Util.dateTimeToInternalFormat(fecha).substring(2, 16).replace(" ", "&nbsp;");
                String mn  = Util.lpad(Util.formatDecimal(monto),9,' ').replace(" ", "&nbsp;");
                String es  = estado.substring(0, 5).replace(" ", "&nbsp;");
                
                return "<html>"+fh+mn+"<span style='color:"+color+"'> "+es+"</span></html>";
            } catch (Exception e) {}
            return "Error al mostrar venta: "+info.get("id");
        }
        
    }
    
    
}
