package com.lasopro.ministore.desktop;

import com.lasopro.ministore.util.DBUtils;
import com.lasopro.ministore.util.Resources;
import com.lasopro.ministore.util.Util;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author williams
 */
public class PanelReportes extends javax.swing.JPanel implements PanelInterface{

    private Map<String,String> reportes;
    private DBUtils db;
    private JFileChooser fileChooser;
    private List<Map<String,Object>> lastResult;
    
    /**
     * Creates new form PanelReportes
     */
    public PanelReportes() {
        initComponents();
    }
    
    @Override
    public String name() {
        return "reportes";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar reporte -", "Reporte de ventas diarias" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        MinistoreDesktop.runInThread("Preparando la información del reporte...",()->{
            mostrarReporte();
        });
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        toCsvFile();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        MinistoreDesktop.runInThread("Actualizando reportes...", () -> {
            _refresh();
        });
    }

    public void _refresh() {
        try {
            reportes = parseReportFile(Resources.p("app.db.type")+".reports.sql");

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

            model.addElement(" - Seleccionar reporte - ");

            for(String k: reportes.keySet()){
                model.addElement(k);
            }
            jComboBox1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los reportes: "+e.getMessage());
            e.printStackTrace();
        }
    }
    
    
    public void mostrarReporte(){
        String titulo = (String)jComboBox1.getSelectedItem();
        String query = reportes.get(titulo);
        jTextPane1.setText("");
        if(query == null){
            return;
        }
        
        if(db == null){
            db  = new DBUtils(MinistoreDesktop.log);
        }
        
        jTextPane1.setText("Cargando datos...");
        
        try{
            lastResult = db.queryAsMap("default", query);

            if(lastResult != null  && !lastResult.isEmpty()){
                String html = toHtmlTable(titulo, lastResult);
                jTextPane1.setText(html);
            } else {
                jTextPane1.setText(toHtmlEmpty(titulo));
            }
        }catch(Throwable err){
            jTextPane1.setText("Se genero un error: "+err.getMessage()+": "+err.getClass().getName());
        }
            
        
    }
    
    


    public static Map<String, String> parseReportFile(String path) throws IOException {

        List<String> lines = Files.readAllLines(Paths.get("res",path));

        Map<String, String> reportes = new LinkedHashMap<>();

        String nombreActual = null;
        StringBuilder queryActual = new StringBuilder();

        for (String line : lines) {

            line = line.trim();

            // 🔹 Detecta nuevo reporte
            if (line.startsWith("#REPORTE:")) {

                // Guardar el anterior
                if (nombreActual != null) {
                    reportes.put(nombreActual, queryActual.toString().trim());
                    queryActual.setLength(0);
                }

                nombreActual = line.replace("#REPORTE:", "").trim();
                continue;
            }

            // 🔹 Ignorar comentarios tipo --
            if (line.startsWith("--") || line.isEmpty()) {
                continue;
            }

            // 🔹 Acumular SQL
            queryActual.append(line).append(" ");
        }

        // 🔹 Guardar último
        if (nombreActual != null) {
            reportes.put(nombreActual, queryActual.toString().trim());
        }

        return reportes;
    }
    
    
    public void toCsvFile() {

        List<Map<String, Object>> data = lastResult;
        
        if (data == null || data.isEmpty()) {
             JOptionPane.showMessageDialog(this, "No hay información para escribir en el reporte");
             return;
        }
        
        
        if (fileChooser == null) {
            this.fileChooser = new JFileChooser();
        }
        this.fileChooser.showSaveDialog(this);

        File selected = this.fileChooser.getSelectedFile();

        if (selected == null) {
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(selected));) {

            

            Map<String, Object> firstRow = data.get(0);
            int count = 0;
            for (String key : firstRow.keySet()) {
                writer.append("\"")
                        .append(key.replace('"', '\'')
                                .replace('\r', ' ')
                                .replace('\n', ' ')
                                .replace(',', '.'))
                        .append("\"");
                count++;
                if(count < firstRow.size()){
                    writer.append(",");
                }
            }
            
            writer.append("\r\n");

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            DecimalFormat decimalFormat = new DecimalFormat("#0.00");

            for (Map<String, Object> row : data) {
                count = 0;
                for (Object value : row.values()) {
                    writer.append("\"").append(formatValue(value, null, dateFormat, decimalFormat).replace(',', '.')).append("\"");
                    count++;
                    if(count < row.size()){
                        writer.append(",");
                    }
                }
                writer.append("\r\n");
            }
            
            writer.flush();
            
            
            JOptionPane.showMessageDialog(this, "Archivo guardado: "+selected.getAbsolutePath(), "Archivo guardado", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException err) {
            JOptionPane.showMessageDialog(this, "Error al generar el archivo: "+err.getMessage(), "Error al generar el archivo", JOptionPane.ERROR_MESSAGE);
            MinistoreDesktop.log.err("Error al generar el archivo: "+err.getMessage(), err);

        }

    }
    
    
     public static String toHtmlTable(String title, List<Map<String, Object>> data) {

        if (data == null || data.isEmpty()) {
            return toHtmlEmpty(title);
        }

        String displayTitle = title.replace("[G]", "").trim();
        boolean withChart = title.contains("[G]");
        String generatedAt = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date());

        StringBuilder html = new StringBuilder();
        html.append("<html><head><style>");
        html.append("body{font-family:Arial,sans-serif;font-size:12px;color:#2c3e50;margin:0;padding:12px;background:#ffffff;}");
        html.append(".header{background-color:#879aae;color:#ffffff;padding:14px 18px;margin-bottom:10px;}");
        html.append(".header h2{margin:0;font-size:18px;font-weight:bold;}");
        html.append(".meta{color:#5d6d7e;font-size:11px;margin:0 0 12px 0;padding:0 4px;}");
        html.append("table.data{border-collapse:collapse;width:100%;margin-bottom:16px;}");
        html.append("table.data th{background-color:#2e5978;color:#ffffff;padding:9px 12px;text-align:left;font-size:11px;text-transform:uppercase;}");
        html.append("table.data td{padding:7px 12px;border-bottom:1px solid #dde4ea;font-size:12px;}");
        html.append("table.data tr.even td{background-color:#f4f7fa;}");
        html.append("table.data tr.total td{font-weight:bold;background-color:#e3ebf3;border-top:2px solid #879aae;border-bottom:none;}");
        html.append("td.num{text-align:right;font-family:Consolas,monospace;}");
        html.append(".chart-box{margin-top:8px;padding:14px;background-color:#fafbfc;border:1px solid #dde4ea;}");
        html.append(".chart-title{font-weight:bold;color:#2e5978;margin-bottom:8px;font-size:13px;}");
        html.append("</style></head><body>");

        html.append("<div class='header'><h2>").append(escapeHtml(displayTitle)).append("</h2></div>");
        html.append("<div class='meta'>Generado: ").append(generatedAt)
                .append(" &nbsp;|&nbsp; Registros: ").append(data.size()).append("</div>");

        Map<String, Object> firstRow = data.get(0);
        Set<String> columns = firstRow.keySet();
        List<String> numericColumns = new ArrayList<>();
        List<String> summableColumns = new ArrayList<>();

        html.append("<table class='data'><tr>");
        for (String key : columns) {
            html.append("<th>").append(escapeHtml(formatColumnHeader(key))).append("</th>");
            if (isNumericColumn(key, data)) {
                numericColumns.add(key);
                if (isSummableColumn(key)) {
                    summableColumns.add(key);
                }
            }
        }
        html.append("</tr>");

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat decimalFormat = new DecimalFormat("#,##0.00");

        int rowIndex = 0;
        Map<String, Double> totals = new LinkedHashMap<>();
        summableColumns.forEach(c -> totals.put(c, 0.0));

        for (Map<String, Object> row : data) {
            String rowClass = (rowIndex % 2 == 0) ? "" : " class='even'";
            html.append("<tr").append(rowClass).append(">");
            for (String key : columns) {
                Object value = row.get(key);
                boolean numeric = value instanceof Number;
                html.append("<td").append(numeric ? " class='num'" : "").append(">");
                html.append(formatValue(value, key, dateFormat, decimalFormat));
                html.append("</td>");
                if (numeric && totals.containsKey(key)) {
                    totals.put(key, totals.get(key) + ((Number) value).doubleValue());
                }
            }
            html.append("</tr>");
            rowIndex++;
        }

        if (!summableColumns.isEmpty()) {
            html.append("<tr class='total'>");
            boolean firstCol = true;
            for (String key : columns) {
                html.append("<td").append(totals.containsKey(key) ? " class='num'" : "").append(">");
                if (firstCol) {
                    html.append("Total");
                    firstCol = false;
                } else if (totals.containsKey(key)) {
                    html.append(formatValue(totals.get(key), key, dateFormat, decimalFormat));
                }
                html.append("</td>");
            }
            html.append("</tr>");
        }

        html.append("</table>");

        if (withChart) {
            String chartPath = generarGraficoHtml(displayTitle, data);
            if (chartPath != null) {
                html.append("<div class='chart-box'>");
                html.append("<div class='chart-title'>Gráfico</div>");
                html.append("<img src='file:").append(chartPath).append("'/>");
                html.append("</div>");
            }
        }

        html.append("</body></html>");
        return html.toString();
    }

    private static String toHtmlEmpty(String title) {
        String displayTitle = title == null ? "Reporte" : title.replace("[G]", "").trim();
        return "<html><body style='font-family:Arial,sans-serif;padding:20px;color:#5d6d7e;'>"
                + "<div style='background-color:#879aae;color:#fff;padding:14px 18px;'>"
                + "<b style='font-size:16px;'>" + escapeHtml(displayTitle) + "</b></div>"
                + "<p style='margin-top:16px;'>No se encontraron datos para este reporte.</p>"
                + "</body></html>";
    }

    public static String generarGraficoHtml(String chartTitle, List<Map<String, Object>> data) {
        BufferedImage image = crearImagenGrafico(chartTitle, data);
        if (image == null) {
            return null;
        }

        try {
            File tempFile = File.createTempFile("grafico_", ".png");
            tempFile.deleteOnExit();
            ImageIO.write(image, "png", tempFile);
            return tempFile.getAbsolutePath();
        } catch (Exception e) {
            return null;
        }
    }

    public static String generarGraficoHtml(List<Map<String, Object>> data) {
        return generarGraficoHtml("Gráfico", data);
    }

    private static BufferedImage crearImagenGrafico(String chartTitle, List<Map<String, Object>> data) {
        if (data == null || data.isEmpty()) {
            return null;
        }

        int barSlot = Math.max(48, Math.min(90, 900 / data.size()));
        int width = Math.max(640, Math.min(1200, barSlot * data.size() + 80));
        int height = 420;
        int paddingLeft = 58;
        int paddingRight = 24;
        int paddingTop = 40;
        int paddingBottom = 16;
        int labelHeight = 56;

        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        g.setColor(Color.WHITE);
        g.fillRect(0, 0, width, height);

        List<String> labels = new ArrayList<>();
        List<Double> values = new ArrayList<>();

        for (Map<String, Object> row : data) {
            Iterator<Object> it = row.values().iterator();
            if (!it.hasNext()) {
                continue;
            }
            String label = String.valueOf(it.next());
            if (label.length() > 14) {
                label = label.substring(0, 14);
            }
            if (!it.hasNext()) {
                continue;
            }
            double value = Double.parseDouble(String.valueOf(it.next()));
            value = BigDecimal.valueOf(value).setScale(2, RoundingMode.HALF_UP).doubleValue();
            labels.add(label);
            values.add(value);
        }

        if (values.isEmpty()) {
            g.dispose();
            return null;
        }

        double max = values.stream().mapToDouble(v -> v).max().orElse(1);
        if (max <= 0) {
            max = 1;
        }

        int chartTop = paddingTop + 12;
        int chartBottom = height - labelHeight - paddingBottom;
        int chartHeight = chartBottom - chartTop;
        int chartWidth = width - paddingLeft - paddingRight;
        int barWidth = Math.max(16, chartWidth / values.size());

        g.setFont(new Font("Arial", Font.BOLD, 14));
        g.setColor(new Color(46, 89, 120));
        g.drawString(chartTitle, paddingLeft, 24);

        g.setFont(new Font("Arial", Font.PLAIN, 9));
        for (int i = 0; i <= 5; i++) {
            int y = chartBottom - (int) (chartHeight * i / 5.0);
            g.setColor(new Color(220, 220, 220));
            g.drawLine(paddingLeft, y, width - paddingRight, y);
            g.setColor(new Color(120, 120, 120));
            g.drawString(formatChartNumber(max * i / 5.0), 4, y + 4);
        }

        g.setColor(new Color(150, 150, 150));
        g.drawLine(paddingLeft, chartTop, paddingLeft, chartBottom);
        g.drawLine(paddingLeft, chartBottom, width - paddingRight, chartBottom);

        Color barColorTop = new Color(135, 170, 206);
        Color barColorBottom = new Color(46, 89, 120);

        for (int i = 0; i < values.size(); i++) {
            int barHeight = (int) ((values.get(i) / max) * chartHeight);
            int x = paddingLeft + i * barWidth + 4;
            int y = chartBottom - barHeight;
            int bw = Math.max(8, barWidth - 8);

            GradientPaint gradient = new GradientPaint(x, y, barColorTop, x, chartBottom, barColorBottom);
            g.setPaint(gradient);
            g.fill(new RoundRectangle2D.Double(x, y, bw, barHeight, 6, 6));

            g.setColor(new Color(46, 89, 120));
            g.setFont(new Font("Arial", Font.BOLD, 9));
            String valueLabel = formatChartNumber(values.get(i));
            FontMetrics fm = g.getFontMetrics();
            int valueX = x + (bw - fm.stringWidth(valueLabel)) / 2;
            g.drawString(valueLabel, Math.max(paddingLeft, valueX), Math.max(chartTop + 8, y - 4));

            g.setColor(new Color(60, 60, 60));
            g.setFont(new Font("Arial", Font.PLAIN, 10));
            String label = labels.get(i);
            if (barWidth < 42 || label.length() > 8) {
                AffineTransform original = g.getTransform();
                g.rotate(-Math.PI / 2);
                g.drawString(label, -(chartBottom + 42), x + bw / 2 + 3);
                g.setTransform(original);
            } else {
                int labelX = x + (bw - g.getFontMetrics().stringWidth(label)) / 2;
                g.drawString(label, labelX, chartBottom + 16);
            }
        }

        g.dispose();
        return image;
    }

    private static String formatColumnHeader(String key) {
        if (key == null) {
            return "";
        }
        return key.replace('_', ' ');
    }

    private static boolean isNumericColumn(String key, List<Map<String, Object>> data) {
        if (key == null || data.isEmpty()) {
            return false;
        }
        Object sample = data.get(0).get(key);
        if (sample instanceof Number) {
            return true;
        }
        String lower = key.toLowerCase();
        return lower.contains("total") || lower.contains("stock") || lower.contains("cantidad")
                || lower.contains("precio") || lower.contains("monto") || lower.contains("ganancia")
                || lower.contains("promedio") || lower.contains("minimo") || lower.contains("maximo");
    }

    private static boolean isSummableColumn(String key) {
        if (key == null) {
            return false;
        }
        String k = key.toLowerCase();
        return !(k.contains("promedio") || k.contains("minimo") || k.contains("maximo")
                || k.contains("porcentaje") || k.contains("dias_con"));
    }

    private static String formatChartNumber(double value) {
        if (Math.abs(value) >= 1_000_000) {
            return new DecimalFormat("#,##0.0").format(value / 1_000_000) + "M";
        }
        if (Math.abs(value) >= 1_000) {
            return new DecimalFormat("#,##0.0").format(value / 1_000) + "K";
        }
        if (value == Math.floor(value)) {
            return String.valueOf((long) value);
        }
        return new DecimalFormat("#,##0.##").format(value);
    }
     
    
     
    
     

    private static String formatValue(Object value,
                                      String columnKey,
                                      SimpleDateFormat dateFormat,
                                      DecimalFormat decimalFormat) {

        if (value == null) {
            return "";
        }

        if (value instanceof Date) {
            return dateFormat.format((Date) value);
        }

        if (value instanceof Number) {
            if (isMoneyColumn(columnKey)) {
                return Util.formatoMonto((Number) value);
            }
            return decimalFormat.format(((Number) value).doubleValue());
        }

        return escapeHtml(value.toString());
    }

    private static boolean isMoneyColumn(String key) {
        if (key == null) {
            return false;
        }
        String k = key.toLowerCase();
        return k.contains("total") || k.contains("precio") || k.contains("monto")
                || k.contains("ganancia") || k.contains("inversion") || k.contains("recuper")
                || k.contains("percibido") || k.contains("descuento");
    }

    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text
                .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace('"', ' ').replace('\r', ' ').replace('\n', ' ');
    }
}
